name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]  # Trigger on push to main branch

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://USER:$HF_TOKEN@huggingface.co" > ~/.git-credentials
          git remote add hf https://huggingface.co/spaces/Ayush9631/DualMarkPrototype
          git push hf main --force